### ISSUE TITLE
Crashed.

### ISSUE THREAD

**Issue by jadenquinn** [thekdub/IC2-Refined#5]
https://mclo.gs/RnJVulD
All I did was try to add the mod in replacement for normal IC2.

**Comment by thekdub** [comment]
Did you try to install this on a client or server? The logs you posted look like it's a client to me.

This project is intended for server use only, and is untested on clients.

**Comment by jadenquinn** [comment]
Ok... so what would someone even use this for then? If it's only intended for the server, what in the world would the client run?

**Comment by thekdub** [comment]
The client would still run the regular copy of IC2.

All changes made here maintain compatibility with stock clients while improving performance on the server's side.
