### ISSUE TITLE
Absence

### ISSUE THREAD

**Issue by hypothermic** [thekdub/IC2-Refined#6]
Hi, I received an email notification that you @mentioned me in the UT discord server and I want to let you know why I can't respond.
This is the only other platform we follow each other on, so I figured I'd open an issue ;)

I currently cannot access my Discord account because I lost the 2FA keys last year (mid-December.)
I'm trying to get Discord support to reset the 2FA because my phone number and email are still linked to the account.

P.S. I don't have much time nowadays anyway so—as I said earlier this year—you can deboat me if you want :)
Though I -am- interested in bare metal graphics and Vulkan so I might create a little voxel rendering engine soon...

**Comment by thekdub** [comment]
That works I guess lol. Hope that Discord will get you back into your account!

I'll keep an eye out for that!

**Comment by boydtech761** [comment]
Message https://t.me/boydtech on telegram he’s the best on account recoveries
